[info]
game-name = "twwgz"
full-game-name = "The Wind Waker Practice Rom"
developer-name = "The Wind Waker / Twilight Princess Community"
full-developer-name = "The Wind Waker / Twilight Princess Community"

[src]
iso = "GZLJ01.iso"
patch = "regional-patch.asm"
map = "maps/framework.map"

[build]
map = "build/GZLJ01.map"
iso = "build/twwgz.iso"

[link]
entries = ["apply_lib_hooks"]
base = "0x8040_1000"
libs = ["twwgz.a", "external/gcn_c/gcn_c.a"]

[files]
# textures
"twwgz/tex/blank.tex" = "res/tex/blank.tex"

# fonts
"twwgz/fonts/consola.fnt" = "res/fonts/consola.fnt"
"twwgz/fonts/calamity-bold.fnt" = "res/fonts/calamity-bold.fnt"
"twwgz/fonts/lib-sans-bold.fnt" = "res/fonts/lib-sans-bold.fnt"
"twwgz/fonts/lib-sans.fnt" = "res/fonts/lib-sans.fnt"
"twwgz/fonts/lib-serif-bold.fnt" = "res/fonts/lib-serif-bold.fnt"
"twwgz/fonts/lib-serif.fnt" = "res/fonts/lib-serif.fnt"
"twwgz/fonts/press-start-2p.fnt" = "res/fonts/press-start-2p.fnt"